FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    software-properties-common \
    && add-apt-repository ppa:deadsnakes/ppa -y \
    && apt-get update \
    && apt-get install -y \
    python3.10 \
    python3.10-venv \
    python3.10-dev \
    python3-pip \
    build-essential \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1 \
    && update-alternatives --set python3 /usr/bin/python3.10

WORKDIR /app

COPY requirements.txt /app
RUN pip install -r requirements.txt

COPY api.py /app
COPY download_models.py /app
COPY ./docs /app/docs
COPY ./conf /app/conf
COPY ./utils /app/utils

RUN python3 /app/download_models.py

COPY entrypoint.sh /app/
RUN chmod +x /app/entrypoint.sh

VOLUME /app/models