services:
  server_1:
    image: server:latest
    environment:
      det_conf: ${det_conf}
    ipc: host
    ports:
      - "1010:5050"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: -1
              capabilities: [gpu]
    command: python api.py
    logging:
      driver: "local"
      options:
        max-size: "100m"
        max-file: "14"
    networks:
      - loadbalance_net

  server_2:
    image: server:latest
    environment:
      det_conf: ${det_conf}
    ipc: host
    ports:
      - "2020:5050"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: -1
              capabilities: [gpu]
    command: python api.py
    logging:
      driver: "local"
      options:
        max-size: "100m"
        max-file: "14"
    networks:
      - loadbalance_net

  server_3:
    image: server:latest
    environment:
      det_conf: ${det_conf}
    ipc: host
    ports:
      - "3030:5050"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: -1
              capabilities: [gpu]
    command: python api.py
    logging:
      driver: "local"
      options:
        max-size: "100m"
        max-file: "14"
    networks:
      - loadbalance_net

  server_4:
    image: server:latest
    environment:
      det_conf: ${det_conf}
    ipc: host
    ports:
      - "4040:5050"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: -1
              capabilities: [gpu]
    command: python api.py
    logging:
      driver: "local"
      options:
        max-size: "100m"
        max-file: "14"
    networks:
      - loadbalance_net

  server_5:
    image: server:latest
    environment:
      det_conf: ${det_conf}
    ipc: host
    ports:
      - "6060:5050"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: -1
              capabilities: [gpu]
    command: python api.py
    logging:
      driver: "local"
      options:
        max-size: "100m"
        max-file: "14"
    networks:
      - loadbalance_net

  nginx_server:
    image: nginx_load_balancer
    ports:
      - "2486:80"
    networks:
      - loadbalance_net
    logging:
      driver: "local"
      options:
        max-size: "100m"
        max-file: "14"

networks:
  loadbalance_net:
    driver: bridge
