version: "3.8"

services:
  translator:
    image: translator:v1.0.0
    volumes:
      - /tmp:/tmp
      - /logs:/app/logs
    environment:
      - GPU_ID=0
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      replicas: 5
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: any
    ipc: host
    ports:
      - target: 5050
        protocol: tcp
        mode: ingress
    command: python3 api.py
    logging:
      driver: "local"
      options:
        max-size: "100m"
        max-file: "14"
    networks:
      - loadbalance_net

  nginx_load_balancer:
    image: nginx_load_balancer:v1.0.3
    volumes:
      - ./tmp/tmp_nginx:/tmp
      - ./logs/logs_nginx:/app/logs
    ports:
      - "2486:80"
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: any
    networks:
      - loadbalance_net
    logging:
      driver: "local"
      options:
        max-size: "100m"
        max-file: "14"

networks:
  loadbalance_net:
    driver: overlay
    attachable: true
